# build.ps1 — STCTI mission builder.
#
# Stamps the canonical framework/ (shared logic) plus each map's per-map data
# (maps/<Map>/mapData.sqf + mission.sqm) into a playable STCTI.<Map>/ mission folder.
#
#   EDIT:   framework/**  and  maps/<Map>/{mapData.sqf,mission.sqm}
#   NEVER:  STCTI.<Map>/**   (regenerated here every build — hand edits are lost)
#
# Run from the repo root:  pwsh ./build.ps1   (or right-click > Run with PowerShell)
# This keeps one source of truth and prevents the per-map logic drift the design doc
# warns about in §14. Migrate to a real @stcti addon at Phase 7 (multi-map rollout).

$ErrorActionPreference = "Stop"
$root      = $PSScriptRoot
$framework = Join-Path $root "framework"
$mapsDir   = Join-Path $root "maps"

if (-not (Test-Path $framework)) { throw "framework/ not found at $framework" }
if (-not (Test-Path $mapsDir))   { throw "maps/ not found at $mapsDir" }

$built = 0
Get-ChildItem $mapsDir -Directory | ForEach-Object {
    $map     = $_.Name
    $mapSrc  = $_.FullName
    $out     = Join-Path $root "STCTI.$map"
    $data    = Join-Path $mapSrc "mapData.sqf"
    $sqm     = Join-Path $mapSrc "mission.sqm"

    if (-not (Test-Path $data)) { Write-Warning "skip $map - no mapData.sqf"; return }
    if (-not (Test-Path $sqm))  { Write-Warning "skip $map - no mission.sqm";  return }

    Write-Host "Building STCTI.$map ..."

    # Keep the folder node itself (a junction may point at it); clear only its contents.
    if (-not (Test-Path $out)) { New-Item -ItemType Directory -Path $out | Out-Null }
    Get-ChildItem $out -Force | Remove-Item -Recurse -Force

    # 1) shared framework  2) per-map data + mission
    Copy-Item (Join-Path $framework "*") $out -Recurse -Force
    Copy-Item $data $out -Force
    Copy-Item $sqm  $out -Force

    Set-Content (Join-Path $out "_GENERATED.txt") `
        "GENERATED by build.ps1 from framework/ + maps/$map/. Do not hand-edit - changes are overwritten."

    $fnCount = (Get-ChildItem (Join-Path $out "functions") -Recurse -Filter *.sqf).Count
    Write-Host "  -> STCTI.$map  ($fnCount functions stamped)"
    $script:built++
}

Write-Host "Done. Built $built mission(s)."
